from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BillViewSet

# Create router and register viewsets
router = DefaultRouter()
router.register(r'bills', BillViewSet)

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
    
    # Additional URL patterns can be added here if needed
    # For example, custom endpoints that don't fit the viewset pattern
]

# URL patterns generated by the router:
# GET/POST     /api/bills/                           - List bills / Create bill
# GET/PUT/PATCH/DELETE /api/bills/{id}/             - Retrieve/Update/Delete specific bill
# GET          /api/bills/by-customer/               - Bills by customer (requires customer_id param)
# GET          /api/bills/by-service/                - Bills by service (requires service_id param) 
# GET          /api/bills/by-purchase/               - Bills by purchase (requires purchase_id param)
# GET          /api/bills/by-shop/                   - Bills by shop (requires shop_id param)
# GET          /api/bills/pending/                   - All pending bills
# GET          /api/bills/paid/                      - All paid bills
# GET          /api/bills/overdue/                   - All overdue bills
# GET          /api/bills/statistics/                - Bill statistics
# POST         /api/bills/{id}/mark-paid/            - Mark bill as paid
# POST         /api/bills/{id}/cancel/               - Cancel bill
# GET          /api/bills/{id}/summary/              - Get bill summary
# POST         /api/bills/bulk-mark-paid/            - Mark multiple bills as paid
# GET          /api/bills/monthly-report/            - Monthly bill report
# GET          /api/bills/recent/                    - Recent bills (last 30 days)