from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TechnicalModelViewSet

# Create router and register viewsets
router = DefaultRouter()
router.register(r'technical-models', TechnicalModelViewSet)

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
    
    # Additional URL patterns can be added here if needed
    # For example, custom endpoints that don't fit the viewset pattern
]

# URL patterns generated by the router:
# GET/POST     /api/technical-models/                     - List technical models / Create technical model
# GET/PUT/PATCH/DELETE /api/technical-models/{id}/       - Retrieve/Update/Delete specific technical model
# GET          /api/technical-models/by-product/          - Technical models by product (requires product_id param)
# GET          /api/technical-models/by-shop/             - Technical models by shop (requires shop_id param)  
# GET          /api/technical-models/by-brand/            - Technical models by brand (requires brand_name param)
# GET          /api/technical-models/active/              - All active technical models
# GET          /api/technical-models/discontinued/        - All discontinued technical models
# GET          /api/technical-models/search-models/       - Search technical models (requires q param)
# GET          /api/technical-models/brands/              - List all brands with statistics
# GET          /api/technical-models/statistics/          - Technical model statistics
# GET          /api/technical-models/{id}/summary/        - Get technical model summary
# POST         /api/technical-models/{id}/mark-discontinued/ - Mark technical model as discontinued
# POST         /api/technical-models/{id}/reactivate/     - Reactivate technical model
# GET/POST     /api/technical-models/{id}/specifications/ - Get/Update specifications
# POST         /api/technical-models/{id}/add-specification/ - Add single specification
# DELETE       /api/technical-models/{id}/clear-specifications/ - Clear all specifications
# GET          /api/technical-models/recent/              - Recent technical models (last 30 days)
# POST         /api/technical-models/bulk-discontinue/    - Mark multiple technical models as discontinued
# POST         /api/technical-models/bulk-reactivate/     - Reactivate multiple technical models