from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router for ViewSet
router = DefaultRouter()
router.register(r'services', views.ServiceViewSet, basename='service')

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /api/services/ - List all services
# POST /api/services/ - Create new service
# GET /api/services/{id}/ - Get specific service
# PUT /api/services/{id}/ - Update service
# PATCH /api/services/{id}/ - Partial update service
# DELETE /api/services/{id}/ - Delete service

# Custom action URLs:
# POST /api/services/{id}/update_status/ - Update service status
# POST /api/services/{id}/add_feedback/ - Add customer feedback
# POST /api/services/{id}/toggle_status/ - Toggle service status
# GET /api/services/by_purchase/ - Get services by purchase
# GET /api/services/by_product/ - Get services by product
# GET /api/services/by_customer/ - Get services by customer
# POST /api/services/bulk_create/ - Bulk create services
# GET /api/services/stats/ - Get service statistics
# GET /api/services/overdue/ - Get overdue services
# GET /api/services/warranty/ - Get warranty services
# GET /api/services/today/ - Get today's services