# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechnicalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the technical model",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Brand name of the product",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name/number of the product",
                        max_length=150,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True, help_text="Official model number", max_length=50
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, help_text="Product series name", max_length=100
                    ),
                ),
                (
                    "year_released",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year the model was released", null=True
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True,
                        help_text="Country where the product was manufactured",
                        max_length=100,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer name (may differ from brand)",
                        max_length=150,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical specifications as JSON (dimensions, weight, power, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this technical model is active"
                    ),
                ),
                (
                    "is_discontinued",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this model has been discontinued",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the technical model",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the technical model was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the technical model was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Model",
                "verbose_name_plural": "Technical Models",
                "ordering": ["brand", "model"],
            },
        ),
    ]
