# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Technical", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalmodel",
            name="product",
            field=models.ForeignKey(
                help_text="Reference to the product this technical model belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technical_models",
                to="product.product",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(fields=["brand"], name="Technical_t_brand_6aaeb5_idx"),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(fields=["model"], name="Technical_t_model_9a1bb8_idx"),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(
                fields=["brand", "model"], name="Technical_t_brand_15bd12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(
                fields=["product"], name="Technical_t_product_e29810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(
                fields=["year_released"], name="Technical_t_year_re_9c5c00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalmodel",
            index=models.Index(
                fields=["is_active"], name="Technical_t_is_acti_387ae3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technicalmodel",
            unique_together={("product", "brand", "model")},
        ),
    ]
