# Generated by Django 5.2.6 on 2025-09-27 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(help_text='National Identity Card number', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='NIC must be in format: 123456789V or 123456789012', regex='^(?:\\d{9}[vVxX]|\\d{12})$')])),
                ('customer_id', models.CharField(blank=True, help_text='Custom customer ID', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text='First name', max_length=30)),
                ('last_name', models.CharField(help_text='Last name', max_length=30)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+94771234567' or '0771234567'", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='Customer address')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the customer is verified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the customer is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
    ]
