# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Rapair", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repair",
            name="purchase",
            field=models.ForeignKey(
                help_text="Reference to the purchase this repair is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="purchase.purchase",
            ),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(fields=["date"], name="Rapair_repa_date_f12456_idx"),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(fields=["status"], name="Rapair_repa_status_7724c9_idx"),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(
                fields=["repair_code"], name="Rapair_repa_repair__4d594d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(
                fields=["purchase"], name="Rapair_repa_purchas_4c9183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(
                fields=["repair_type"], name="Rapair_repa_repair__761225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(
                fields=["priority"], name="Rapair_repa_priorit_4c8399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repair",
            index=models.Index(
                fields=["completed_date"], name="Rapair_repa_complet_33f861_idx"
            ),
        ),
    ]
