# Generated by Django 5.2.6 on 2025-09-25 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "wa_number",
                    models.CharField(
                        help_text="WhatsApp number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="WhatsApp number must be in format: '+94771234567' or '0771234567'",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "tp_number",
                    models.CharField(
                        help_text="Telephone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telephone number must be in format: '+94112345678' or '0112345678'",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary contact?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this contact active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Contact",
                "verbose_name_plural": "Customer Contacts",
                "db_table": "customer_contacts",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "email"), name="unique_customer_email"
                    ),
                    models.UniqueConstraint(
                        fields=("customer", "wa_number"),
                        name="unique_customer_wa_number",
                    ),
                    models.UniqueConstraint(
                        fields=("customer", "tp_number"),
                        name="unique_customer_tp_number",
                    ),
                ],
            },
        ),
    ]
