# Generated by Django 5.2.6 on 2025-09-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(help_text='Customer reference', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.customer'),
        ),
    ]
