# Generated by Django 5.2.6 on 2025-09-25 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Shop name", max_length=255)),
                (
                    "postal_code",
                    models.CharField(
                        help_text="5-digit postal code",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be 5 digits", regex="^\\d{5}$"
                            )
                        ],
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="Address line 1 (Street address, building number)",
                        max_length=255,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address line 2 (Apartment, suite, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line_3",
                    models.CharField(
                        blank=True,
                        help_text="Address line 3 (Additional address information)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("city", models.CharField(help_text="City name", max_length=100)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is the shop active?"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Shop phone number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Shop email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Shop description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who owns this shop",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "db_table": "shops",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "name"), name="unique_customer_shop_name"
                    )
                ],
            },
        ),
    ]
