# Generated by Django 5.2.6 on 2025-09-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '__first__'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='customer',
            field=models.ForeignKey(help_text='Customer who owns this shop', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='customer.customer'),
        ),
    ]
