from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router for ViewSet
router = DefaultRouter()
router.register(r'purchases', views.PurchaseViewSet, basename='purchase')

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /api/purchases/ - List all purchases
# POST /api/purchases/ - Create new purchase
# GET /api/purchases/{id}/ - Get specific purchase
# PUT /api/purchases/{id}/ - Update purchase
# PATCH /api/purchases/{id}/ - Partial update purchase
# DELETE /api/purchases/{id}/ - Delete purchase

# Custom action URLs:
# POST /api/purchases/{id}/update_payment_status/ - Update payment status
# POST /api/purchases/{id}/toggle_status/ - Toggle purchase status
# GET /api/purchases/by_customer/ - Get purchases by customer
# GET /api/purchases/by_product/ - Get purchases by product
# POST /api/purchases/bulk_create/ - Bulk create purchases
# GET /api/purchases/stats/ - Get purchase statistics
# GET /api/purchases/today/ - Get today's purchases
# GET /api/purchases/recent/ - Get recent purchases