# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the license",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "in_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the license was issued",
                    ),
                ),
                (
                    "ex_date",
                    models.DateTimeField(help_text="Date when the license expires"),
                ),
                (
                    "license_key",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated license key",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("trial", "Trial License"),
                            ("standard", "Standard License"),
                            ("premium", "Premium License"),
                            ("enterprise", "Enterprise License"),
                            ("educational", "Educational License"),
                            ("commercial", "Commercial License"),
                            ("personal", "Personal License"),
                            ("developer", "Developer License"),
                        ],
                        default="standard",
                        help_text="Type of license",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("pending", "Pending Activation"),
                        ],
                        default="pending",
                        help_text="Current status of the license",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated license number",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "software_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the software/product being licensed",
                        max_length=150,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Version of the software", max_length=50
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of users allowed"
                    ),
                ),
                (
                    "max_installations",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of installations allowed"
                    ),
                ),
                (
                    "features_enabled",
                    models.JSONField(
                        blank=True, default=list, help_text="List of enabled features"
                    ),
                ),
                (
                    "restrictions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="License restrictions and limitations",
                    ),
                ),
                (
                    "activated_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the license was activated",
                        null=True,
                    ),
                ),
                (
                    "activation_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times license has been activated",
                    ),
                ),
                (
                    "last_used_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the license was last used",
                        null=True,
                    ),
                ),
                (
                    "usage_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Usage statistics and data"
                    ),
                ),
                (
                    "support_expires",
                    models.DateTimeField(
                        blank=True, help_text="Date when support expires", null=True
                    ),
                ),
                (
                    "maintenance_expires",
                    models.DateTimeField(
                        blank=True, help_text="Date when maintenance expires", null=True
                    ),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(
                        default=False, help_text="Whether license auto-renews"
                    ),
                ),
                (
                    "renewal_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for license renewal",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "licensed_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of the license holder",
                        max_length=200,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="Organization name", max_length=200
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for license holder",
                        max_length=254,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the license"
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether license terms have been accepted",
                    ),
                ),
                (
                    "terms_accepted_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when terms were accepted", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the license was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the license was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "ordering": ["-in_date", "-created_at"],
            },
        ),
    ]
