# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("license", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="purchase",
            field=models.ForeignKey(
                help_text="Reference to the purchase this license is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="purchase.purchase",
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["in_date"], name="license_lic_in_date_0b247d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["ex_date"], name="license_lic_ex_date_5e1c83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="license_lic_status_2b6faf_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key"], name="license_lic_license_182969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_number"], name="license_lic_license_69d407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["purchase"], name="license_lic_purchas_bec6ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_type"], name="license_lic_license_55c712_idx"
            ),
        ),
    ]
