from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router for ViewSet
router = DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='product')

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /api/products/ - List all products
# POST /api/products/ - Create new product
# GET /api/products/{id}/ - Get specific product
# PUT /api/products/{id}/ - Update product
# PATCH /api/products/{id}/ - Partial update product
# DELETE /api/products/{id}/ - Delete product

# Custom action URLs:
# POST /api/products/{id}/regenerate_qr_code/ - Regenerate QR code
# POST /api/products/{id}/toggle_status/ - Toggle product status
# POST /api/products/bulk_create/ - Bulk create products
# GET /api/products/stats/ - Get product statistics
# GET /api/products/search_by_qr/ - Search by QR code