from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router for ViewSet
router = DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='product')

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
    
    # Additional URLs for specific views
    path('shops/<int:shop_id>/products/', views.ShopProductsView.as_view(), name='shop-products'),
]

# URL patterns generated by the router:
# GET /api/products/ - List all products
# POST /api/products/ - Create new product
# GET /api/products/{id}/ - Get specific product
# PUT /api/products/{id}/ - Update product
# PATCH /api/products/{id}/ - Partial update product
# DELETE /api/products/{id}/ - Delete product

# Custom action URLs:
# POST /api/products/{id}/regenerate_qr_code/ - Regenerate QR code
# GET /api/products/{id}/qr_code_info/ - Get QR code info
# POST /api/products/{id}/toggle_status/ - Toggle product status
# GET /api/products/by_shop/ - Get products by shop
# GET /api/products/by_customer/ - Get products by customer
# POST /api/products/bulk_create/ - Bulk create products
# GET /api/products/stats/ - Get product statistics
# GET /api/products/search_by_qr/ - Search by QR code