# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bill", "0001_initial"),
        ("purchase", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="purchase",
            field=models.ForeignKey(
                help_text="Reference to the purchase this bill is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="purchase.purchase",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="service",
            field=models.ForeignKey(
                help_text="Reference to the service this bill is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["date"], name="bill_bill_date_352c6b_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="bill_bill_status_12cb1e_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["bill_number"], name="bill_bill_bill_nu_f39e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["service"], name="bill_bill_service_f9847b_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["purchase"], name="bill_bill_purchas_923d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["due_date"], name="bill_bill_due_dat_31451d_idx"
            ),
        ),
    ]
