from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import RepairViewSet

# Create router and register viewsets
router = DefaultRouter()
router.register(r'repairs', RepairViewSet)

urlpatterns = [
    # Include router URLs
    path('', include(router.urls)),
    
    # Additional URL patterns can be added here if needed
    # For example, custom endpoints that don't fit the viewset pattern
]

# URL patterns generated by the router:
# GET/POST     /api/repairs/                          - List repairs / Create repair
# GET/PUT/PATCH/DELETE /api/repairs/{id}/            - Retrieve/Update/Delete specific repair
# GET          /api/repairs/by-customer/              - Repairs by customer (requires customer_id param)
# GET          /api/repairs/by-product/               - Repairs by product (requires product_id param)
# GET          /api/repairs/by-purchase/              - Repairs by purchase (requires purchase_id param)
# GET          /api/repairs/by-shop/                  - Repairs by shop (requires shop_id param)
# GET          /api/repairs/active/                   - All active repairs
# GET          /api/repairs/completed/                - All completed repairs
# GET          /api/repairs/overdue/                  - All overdue repairs
# GET          /api/repairs/ready-for-pickup/         - Repairs ready for pickup
# GET          /api/repairs/warranty-repairs/         - All warranty repairs
# GET          /api/repairs/statistics/               - Repair statistics
# GET          /api/repairs/{id}/summary/             - Get repair summary
# POST         /api/repairs/{id}/start-repair/        - Start a repair
# POST         /api/repairs/{id}/complete-repair/     - Complete a repair
# POST         /api/repairs/{id}/deliver/             - Mark repair as delivered
# POST         /api/repairs/{id}/add-part/            - Add part used in repair
# GET          /api/repairs/recent/                   - Recent repairs (last 30 days)
# POST         /api/repairs/bulk-update-status/       - Bulk update repair status
# GET          /api/repairs/technician-workload/      - Technician workload statistics