# Generated by Django 5.2.6 on 2025-09-25 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Auto-generated unique identifier for the product",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name (max 255 characters)",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Product name can only contain letters, numbers, spaces, hyphens, underscores, periods, parentheses, and ampersands",
                                regex="^[a-zA-Z0-9\\s\\-_.()&]+$",
                            )
                        ],
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated QR code for the product",
                        null=True,
                        upload_to="product_qr_codes/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Product description", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product price (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit (SKU) - optional",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the product is active"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0, help_text="Available stock quantity"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="The shop this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"],
                        name="product_pro_shop_id_f77260_idx",
                    ),
                    models.Index(fields=["name"], name="product_pro_name_b60cd1_idx"),
                    models.Index(
                        fields=["created_at"], name="product_pro_created_57e07a_idx"
                    ),
                ],
                "unique_together": {("shop", "name")},
            },
        ),
    ]
